### ISSUE TITLE
[Suggestion] Search track by ISRC

### ISSUE THREAD

**Issue by nullptr448** [Takiyo0/kazagumo-spotify#8]
Making this modification to the plugin should be easy, given that Spotify already provides an [ISRC](https://en.wikipedia.org/wiki/International_Standard_Recording_Code) on it's track object, as seen on the image.

Example for the Track "Tristeza Em Mim" by Sérgio Mendes
![image](https://user-images.githubusercontent.com/72574725/226079307-c5fcf03c-3023-42c7-b1b7-d73dec0121d1.png)

Searching the track's ISRC on Youtube given that it's a unique track identifier, returns more accurate results, with the artist's "topic" channel being the first ytsearch result, this could solve issues with the Youtube equivalent of the Spotify track being a remix, modified version of the track, or not even the original Spotify track at all.

If for some reason the ISRC is missing from Spotify's track object or if searching the ISRC doesn't return any results, the song could be searched for in the traditional way (Sending `ytsearch:ArtistName - TrackTitle` to Lavalink and picking the best match)

**Comment by Xenofic** [comment]
looks interesting might try creating a pr for this

**Comment by otonierusv** [comment]
nah this being open since march. 😒

**Comment by Takiyo0** [comment]
It's done here
https://github.com/Takiyo0/kazagumo-spotify/commit/4853b7b8aa6e584cedfc92108fbda2308a04d899
sorry for the veryyy long response

**Comment by nullptr448** [comment]
Amazing, thanks a lot for implementing this
